// Brand Studio Shared Types
// Extracted from pages/creative-studio.tsx for modularity

export type BrandSnapshot = {
  name: string;
  description: string;
  audience: string;
  offering: string;
  tone: string;
  logo?: string; // URL or data URL
  logoUrl?: string; // Original URL (backup)
  // New BrandProfile fields
  primaryColors?: string[]; // Array of hex codes (e.g., ["#FF0000", "#00FF00"])
  fontStyles?: string; // serif, sans-serif, monospace, etc.
  brandVoice?: "Professional" | "Playful" | "Minimalist" | "Bold"; // Brand voice enum
  coreValueProp?: string; // The "Hook" - main value proposition
  // Legacy color support (for backward compatibility)
  colors?: {
    primary?: string;
    secondary?: string;
    accent?: string;
  };
  industry?: string;
  tagline?: string;
  personality?: string; // confident, friendly, youthful, premium, bold, playful, etc.
  // Expanded Brand Intelligence (excluding visual style and typography - not stored)
  ctaPatterns?: string[]; // Common CTAs like "Shop Now", "Buy Today", "Explore More"
  productCategory?: string; // Specific category like "earbuds", "headphones", "smartwatches"
  pricePositioning?: "budget" | "mid-range" | "premium";
};

export type Phase =
  | "input"
  | "analyzing"
  | "brand-review"
  | "product-input"
  | "poster-prompt"
  | "config"
  | "generating"
  | "ready";

export type StudioMode = "select" | "poster" | "video";

export type SessionType = "poster" | "video";

// Ad Builder Wizard Types
export type AdBuilderStep = 1 | 2 | 3 | 4;

export type ProductData = {
  product_name: string;
  brand_name: string;
  product_images: string[]; // Data URLs
  hero_image: string | null; // Selected image
  brand_logo: string | null; // Logo URL or data URL
  category: string;
  product_url?: string;
};

export type AdSetup = {
  style:
    | "Product Close-up"
    | "Lifestyle"
    | "Cinematic"
    | "Luxury"
    | "Minimalist"
    | "Bold & Energetic"
    | "Stop Motion"
    | "3D Animation"
    | "2D Animation"
    | "Motion Graphics"
    | "Hook"
    | "Retro"
    | "Neon"
    | "Commercial"
    | "UGC Style";
  duration: 8;
  platform: "Instagram Reels / TikTok" | "YouTube Shorts" | "Instagram Feed" | "YouTube Ad";
  aspect_ratio: "9:16" | "1:1" | "16:9" | "4:5";
  quality?: "standard" | "high"; // "standard" = 720p, "high" = 1080p
};

export type VoiceoverConfig = {
  enabled: boolean;
  language?: "english" | "tamil" | "hindi";
  tone: "Energetic" | "Calm" | "Premium" | "Fun";
  key_message?: string;
  cta?: string;
  script?: string; // Generated by AI
  headline?: string; // Generated by AI
  subtext?: string; // Generated by AI
};

/** Text style for on-screen video text (kinetic, animated, captions, etc.) */
export type VideoTextStyle =
  | "kinetic"
  | "animated_titles"
  | "subtitles_captions"
  | "specialized"
  | "animated_effects";

/** Placement for on-screen text (lower third recommended for readability) */
export type VideoTextPosition =
  | "lower_third"
  | "center"
  | "top_third"
  | "full_width";

export type OnScreenText = {
  enabled: boolean;
  headline?: string;
  subtext?: string;
  /** Style: kinetic typography, animated titles, subtitles, specialized, or animated effects */
  textStyle?: VideoTextStyle;
  /** Position: lower third (recommended), center, top third, or full width */
  textPosition?: VideoTextPosition;
  /** Use brand colors/fonts when available for consistency */
  alignBrand?: boolean;
};

export type AdBuilderData = {
  step: AdBuilderStep;
  product: ProductData | null;
  adSetup: AdSetup;
  voiceover: VoiceoverConfig;
  onScreenText: OnScreenText;
  finalVideoPrompt?: string; // Generated by script generator
  userDescription?: string; // User's description of what they want
  storyboard?: Array<{
    scene: number;
    duration: string;
    time_range?: string; // e.g., "0-3s", "3-7s"
    visual_description: string;
    on_screen_text: string;
    emotion: string;
    motion_style: string;
    voiceover_script?: string;
    voiceover_line?: string; // Per-scene voiceover
  }>;
  visualStyleGuide?: {
    color_palette: string;
    lighting_mood: string;
    typography: string;
    motion_style: string;
    brand_polish: string;
  };
  adAngle?: string;
};

export type Message = {
  id: string;
  role: "user" | "system";
  content: string;
  images?: File[];
  imageUrls?: string[]; // For displaying generated poster URLs in chat history
  imageStoragePaths?: string[]; // Parallel to imageUrls — Supabase storage paths for deletion
  expiredImageCount?: number; // How many images were expired/removed (for skeleton UI)
  imageThumbnail?: boolean; // If true, render imageUrls as simple thumbnails (no action buttons)
  timestamp: number;
};

// Serializable version of Message (for storage)
export type SerializedMessage = {
  id: string;
  role: "user" | "system";
  content: string;
  timestamp: number;
  imageUrls?: string[]; // Persist generated poster URLs in chat history
  imageStoragePaths?: string[]; // Supabase storage paths for deletion
  expiredImageCount?: number; // How many images were expired/removed
  imageThumbnail?: boolean; // If true, render imageUrls as simple thumbnails
};

export type UserInput = {
  website?: string;
  text?: string;
  images: File[];
};

export type PosterConfig = {
  theme: string;
  aspectRatio: "1:1" | "4:5" | "9:16" | "1.91:1";
  variantCount: 1 | 2 | 3; // Number of variants to generate (1-3)
};

// Session type for database persistence
export type CreativeStudioSession = {
  id: string;
  userId: string;
  name: string;
  sessionType: SessionType;
  brandSnapshot: BrandSnapshot;
  // Poster-specific fields
  phase?: Phase;
  messages?: SerializedMessage[];
  productData?: {
    prompt: string;
    imageDataUrls?: string[];
  };
  posterPrompt?: string;
  config?: PosterConfig;
  generatedPosters?: string[];
  // Video-specific fields
  adBuilderData?: AdBuilderData;
  generatedVideos?: Array<{
    id: string;
    url: string;
    prompt: string;
    timestamp: number;
  }>;
  // Timestamps
  createdAt: string;
  updatedAt: string;
};

// Legacy chat type (for localStorage compatibility during migration)
export type CreativeStudioChat = {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  // Full chat state
  phase: Phase;
  messages: Message[];
  brand: BrandSnapshot | null;
  productPrompt: string;
  productImages: File[]; // Note: Files can't be serialized, will need to handle differently
  productImageDataUrls?: string[]; // Store data URLs for persistence
  savedProductData: {
    prompt: string;
    images: File[]; // Same issue
    imageDataUrls?: string[]; // Store data URLs for persistence
  } | null;
  posterPrompt: string;
  config: PosterConfig;
  generatedPosters: string[]; // URLs/data URLs
};

// Session list item (for sidebar display)
export type SessionListItem = {
  id: string;
  name: string;
  sessionType: SessionType;
  updatedAt: string;
  createdAt: string;
};

// Generated video type
export type GeneratedVideo = {
  id: string;
  url: string;
  prompt: string;
  timestamp: number;
};
