"use client";

import * as React from "react";
import Sidebar from "../app/web/src/components/Sidebar";
import { Card } from "../app/web/src/components/ui/card";
import colors from "../lib/colors";
import { supabase } from "../lib/supabaseClient";
import { toast } from "sonner";

/**
 * pages/image-library.tsx
 * Minimal image library: shows only images from user_generated_image.image_url for the signed-in user.
 * NavBar removed per request; Sidebar kept.
 */

export default function ImageLibraryPage() {
  const [images, setImages] = React.useState<string[]>([]);
  const [loading, setLoading] = React.useState<boolean>(true);
  const [firstName, setFirstName] = React.useState<string | null>(null);

  React.useEffect(() => {
    let mounted = true;

    const getCurrentUser = async () => {
      try {
        const { data } = await supabase.auth.getUser();
        return (data as any)?.user ?? null;
      } catch (e) {
        return null;
      }
    };

    const fetchImages = async () => {
      if (!mounted) return;
      setLoading(true);
      try {
        const user = await getCurrentUser();
        if (!user) {
          if (mounted) {
            setImages([]);
            setFirstName(null);
            setLoading(false);
          }
          return;
        }

        // Best-effort profile fetch for greeting
        try {
          const { data: profile } = await supabase
            .from("profiles")
            .select("full_name")
            .eq("id", user.id)
            .single();
          const name =
            (profile as any)?.full_name ||
            (user.email ? user.email.split("@")[0] : null);
          if (mounted) setFirstName(name);
        } catch (e) {
          if (mounted) setFirstName(user.email ? user.email.split("@")[0] : "There");
        }

        const { data, error } = await supabase
          .from("user_generated_image")
          .select("image_url")
          .eq("user_id", user.id)
          .order("created_at", { ascending: false })
          .limit(500);

        if (error) {
          console.warn("fetch images error", error);
          toast.error("Failed to fetch images");
          if (mounted) setImages([]);
        } else {
          // ensure we pass string[] only
          const urls = (data || [])
            .map((r: any) => (r && r.image_url ? String(r.image_url) : null))
            .filter((u): u is string => Boolean(u));
          if (mounted) setImages(urls);
        }
      } catch (e) {
        console.error("image library load failed", e);
        toast.error("Failed to load images");
        if (mounted) setImages([]);
      } finally {
        if (mounted) setLoading(false);
      }
    };

    fetchImages();

    return () => {
      mounted = false;
    };
  }, []);

  const greet = React.useMemo(() => {
    const n = firstName ? String(firstName).trim() : null;
    if (!n) return "There";
    const f = n.split(" ")[0];
    return f.charAt(0).toUpperCase() + f.slice(1).toLowerCase();
  }, [firstName]);

  return (
    <div className="min-h-screen flex bg-slate-50">
      {/* Sidebar remains */}
      <Sidebar logoUrl={"/brand/logo.png"} onLogoClick={() => {}} />

      {/* Main content — no NavBar */}
      <div className="flex-1" style={{ marginLeft: 0 }}>
        <main className="max-w-6xl mx-auto p-6 pb-56">
          <div className="mb-6">
            <h2 className="text-2xl font-semibold">Image Library</h2>
            <p className="text-sm mt-1" style={{ color: colors.mutedForeground }}>
              {loading ? "Loading your images…" : `All images generated by ${greet}.`}
            </p>
          </div>

          <Card
            className="p-4 optim-deep-shadow"
            style={{ background: colors.card, border: `1px solid ${colors.border}` }}
          >
            {loading ? (
              <div style={{ color: colors.mutedForeground }}>Loading...</div>
            ) : images.length === 0 ? (
              <div style={{ color: colors.mutedForeground }}>
                No generated images found. Create a campaign to generate images and they'll appear here.
              </div>
            ) : (
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">
                {images.map((src, idx) => (
                  <div key={idx} className="rounded overflow-hidden border" style={{ borderColor: colors.border }}>
                    <img src={src} alt={`generated-${idx}`} className="w-full h-40 object-cover" />
                  </div>
                ))}
              </div>
            )}
          </Card>
        </main>
      </div>
    </div>
  );
}
