"use client";

import * as React from "react";
import Sidebar from "../app/web/src/components/Sidebar"; // adjust if using aliases
import { Card } from "../app/web/src/components/ui/card";
import colors from "../lib/colors";
import { supabase } from "../lib/supabaseClient";
import { toast } from "sonner";

type UserImage = {
  id: string;
  imageUrl: string;
  createdAt: string;
};

export default function ImageLibraryPage() {
  const [images, setImages] = React.useState<UserImage[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [firstName, setFirstName] = React.useState<string | null>(null);
  const [selectedImage, setSelectedImage] = React.useState<UserImage | null>(
    null
  );

  React.useEffect(() => {
    let mounted = true;

    const getCurrentUser = async () => {
      try {
        const { data, error } = await supabase.auth.getUser();
        if (error) return null;
        return data.user ?? null;
      } catch {
        return null;
      }
    };

    const fetchImages = async () => {
      if (!mounted) return;
      setLoading(true);

      try {
        const user = await getCurrentUser();
        if (!user) {
          if (mounted) {
            setImages([]);
            setFirstName(null);
            setLoading(false);
          }
          return;
        }

        // fetch user profile for greeting
        try {
          const { data: profile } = await supabase
            .from("profiles")
            .select("full_name")
            .eq("id", user.id)
            .single();
          const name =
            (profile as any)?.full_name ||
            (user.email ? user.email.split("@")[0] : null);
          if (mounted) setFirstName(name);
        } catch {
          if (mounted)
            setFirstName(user.email ? user.email.split("@")[0] : "There");
        }

        // fetch user images
        const { data, error } = await supabase
          .from("user_generated_image")
          .select("id, image_url, created_at")
          .eq("user_id", user.id)
          .order("created_at", { ascending: false })
          .limit(500);

        if (error) {
          toast.error("Failed to fetch images");
          if (mounted) setImages([]);
        } else {
          const parsed: UserImage[] =
            (data || [])
              .map((r: any) =>
                r && r.image_url
                  ? {
                      id: String(r.id),
                      imageUrl: String(r.image_url),
                      createdAt: String(r.created_at),
                    }
                  : null
              )
              .filter((u): u is UserImage => Boolean(u)) ?? [];
          if (mounted) setImages(parsed);
        }
      } catch {
        toast.error("Failed to load images");
        if (mounted) setImages([]);
      } finally {
        if (mounted) setLoading(false);
      }
    };

    fetchImages();
    return () => {
      mounted = false;
    };
  }, []);

  const greet = React.useMemo(() => {
    const n = firstName?.trim();
    if (!n) return "There";
    const f = n.split(" ")[0];
    return f.charAt(0).toUpperCase() + f.slice(1).toLowerCase();
  }, [firstName]);

  // CTA – DELETE
  const handleDelete = async () => {
    if (!selectedImage) return;
    try {
      const { error } = await supabase
        .from("user_generated_image")
        .delete()
        .eq("id", selectedImage.id);

      if (error) {
        toast.error("Failed to delete image");
        return;
      }

      setImages((prev) => prev.filter((img) => img.id !== selectedImage.id));
      setSelectedImage(null);
      toast.success("Image deleted");
    } catch {
      toast.error("Failed to delete image");
    }
  };

  // CTA – DOWNLOAD
  const handleDownload = () => {
    if (!selectedImage) return;
    const link = document.createElement("a");
    link.href = selectedImage.imageUrl;
    link.download = "poster.png";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // CTA – POST (placeholder)
  const handlePost = async () => {
    if (!selectedImage) return;
    // Replace with API call later if needed
    toast.info("Post action triggered (not wired to backend yet).");
  };

  return (
    <div className="min-h-screen flex bg-slate-50">
      <Sidebar logoUrl="/brand/logo.png" onLogoClick={() => {}} />

      <div className="flex-1" style={{ marginLeft: 0 }}>
        <main className="max-w-6xl mx-auto p-6 pb-56">
          <div className="mb-6">
            <h2 className="text-2xl font-semibold">Image Library</h2>
            <p
              className="text-sm mt-1"
              style={{ color: colors.mutedForeground }}
            >
              {loading
                ? "Loading your images…"
                : `All images generated by ${greet}.`}
            </p>
          </div>

          <Card
            className="p-4 optim-deep-shadow"
            style={{
              background: colors.card,
              border: `1px solid ${colors.border}`,
            }}
          >
            {loading ? (
              <div style={{ color: colors.mutedForeground }}>Loading...</div>
            ) : images.length === 0 ? (
              <div style={{ color: colors.mutedForeground }}>
                No generated images found. Create a campaign to generate images
                and they&apos;ll appear here.
              </div>
            ) : (
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">
                {images.map((img) => (
                  <button
                    key={img.id}
                    onClick={() => setSelectedImage(img)}
                    className="rounded overflow-hidden border focus:ring-2 focus:ring-sky-500"
                    style={{ borderColor: colors.border }}
                  >
                    <img
                      src={img.imageUrl}
                      alt="generated"
                      className="w-full h-40 object-cover"
                    />
                  </button>
                ))}
              </div>
            )}
          </Card>
        </main>
      </div>

      {/* FULL SCREEN VIEWER */}
      {selectedImage && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
          <div className="bg-white rounded-xl max-w-4xl w-full mx-4 p-4 md:p-6 shadow-xl relative">
            <button
              type="button"
              onClick={() => setSelectedImage(null)}
              className="absolute left-4 top-4 px-3 py-1 rounded-full border hover:bg-slate-100"
            >
              ← Back
            </button>

            <div className="mt-8 grid gap-4 md:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)] items-start">
              <div className="w-full">
                <div className="overflow-hidden rounded-lg border">
                  <img
                    src={selectedImage.imageUrl}
                    alt="selected"
                    className="w-full max-h-[70vh] object-contain bg-slate-100"
                  />
                </div>
                <p className="text-xs text-slate-500 mt-2">
                  Created at:{" "}
                  {new Date(selectedImage.createdAt).toLocaleString()}
                </p>
              </div>

              <div className="flex flex-col gap-2">
                <h3 className="text-base font-semibold mb-1">Actions</h3>

                <button
                  onClick={handleDownload}
                  className="w-full px-4 py-2 rounded-md border hover:bg-slate-50"
                >
                  Download
                </button>

                <button
                  onClick={handlePost}
                  className="w-full px-4 py-2 rounded-md border hover:bg-slate-50"
                >
                  Post
                </button>

                <button
                  onClick={handleDelete}
                  className="w-full px-4 py-2 rounded-md border border-red-500 text-red-600 hover:bg-red-50"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
