#!/bin/bash

# Oli AI - Supabase Local Development Setup Script
# This script sets up the local development environment using Supabase
# Supabase provides: PostgreSQL, Auth, Storage, Realtime, Studio

set -e

echo "🚀 Oli AI Local Development Setup"
echo "=================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if Docker is running
echo -e "\n${YELLOW}Checking prerequisites...${NC}"

if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running. Please start Docker first.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Docker is running${NC}"

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo -e "${RED}❌ Supabase CLI not found.${NC}"
    echo ""
    echo "Install with Homebrew (macOS):"
    echo "  brew install supabase/tap/supabase"
    echo ""
    echo "Or with npm:"
    echo "  npm install -g supabase"
    exit 1
fi
echo -e "${GREEN}✓ Supabase CLI installed ($(supabase --version))${NC}"

# Start Supabase
echo -e "\n${YELLOW}Starting Supabase local stack...${NC}"
echo "This includes: PostgreSQL, Auth, Storage, Realtime, Studio"
supabase start

# Get Supabase status
echo -e "\n${BLUE}Supabase connection info:${NC}"
supabase status

# Reset database to apply migrations
echo -e "\n${YELLOW}Applying database migrations...${NC}"
supabase db reset

# Check if .env.local exists
if [ ! -f .env.local ]; then
    echo -e "\n${YELLOW}Creating .env.local from template...${NC}"
    
    # Try to get Supabase keys from status
    ANON_KEY=$(supabase status 2>/dev/null | grep "anon key:" | awk '{print $3}' || echo "")
    SERVICE_KEY=$(supabase status 2>/dev/null | grep "service_role key:" | awk '{print $3}' || echo "")
    
    cat > .env.local << EOF
# ============================================================
# Oli AI Local Development Environment Variables
# Auto-generated by setup script on $(date)
# ============================================================

# DATABASE (Supabase Local PostgreSQL)
DATABASE_URL="postgresql://postgres:postgres@localhost:54322/postgres"

# SUPABASE (Local Development Keys)
NEXT_PUBLIC_SUPABASE_URL="http://localhost:54321"
NEXT_PUBLIC_SUPABASE_ANON_KEY="${ANON_KEY:-run-supabase-status-to-get-key}"
SUPABASE_SERVICE_ROLE_KEY="${SERVICE_KEY:-run-supabase-status-to-get-key}"

# SUPABASE STORAGE (Local)
# Storage is available at: http://localhost:54321/storage/v1
# Buckets configured in supabase/config.toml:
# - campaign-assets (public, images/videos)
# - user-uploads (public, images/videos/pdfs)

# Add your other API keys below:
# META_APP_ID=""
# META_APP_SECRET=""
# GOOGLE_ADS_CLIENT_ID=""
# OPENAI_API_KEY=""
EOF
    echo -e "${GREEN}✓ Created .env.local${NC}"
    echo -e "${YELLOW}⚠️  Please update .env.local with your API keys${NC}"
    
    # If keys weren't auto-detected, remind user
    if [ -z "$ANON_KEY" ] || [ -z "$SERVICE_KEY" ]; then
        echo -e "${YELLOW}⚠️  Run 'supabase status' to get your local API keys${NC}"
    fi
else
    echo -e "${GREEN}✓ .env.local already exists${NC}"
fi

# Summary
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "📍 Supabase Local Services:"
echo "   ┌──────────────────────────────────────────────────┐"
echo "   │  Next.js App:      http://localhost:3000         │"
echo "   │  Supabase Studio:  http://localhost:54323        │"
echo "   │  Supabase API:     http://localhost:54321        │"
echo "   │  PostgreSQL:       localhost:54322               │"
echo "   │  Storage API:      http://localhost:54321/storage│"
echo "   │  Auth API:         http://localhost:54321/auth   │"
echo "   │  Inbucket (Email): http://localhost:54324        │"
echo "   └──────────────────────────────────────────────────┘"
echo ""
echo "🗄️  Storage Buckets (configured in supabase/config.toml):"
echo "   • campaign-assets  - Public, for campaign images/videos"
echo "   • user-uploads     - Public, for user file uploads"
echo ""
echo "🔑 Get Supabase keys:"
echo "   supabase status"
echo ""
echo "🚀 Start development:"
echo "   npm run dev"
echo ""
echo "📚 Documentation:"
echo "   docs/SUPABASE_LOCAL_SETUP.md"
echo ""
echo "🔧 Useful commands:"
echo "   npm run supabase:start   - Start Supabase"
echo "   npm run supabase:stop    - Stop Supabase"
echo "   npm run supabase:reset   - Reset database"
echo "   npm run supabase:status  - Check status"
