// pages/api/creative-studio/generate-video.ts
// Reference: https://ai.google.dev/gemini-api/docs/video?example=dialogue
import type { NextApiRequest, NextApiResponse } from "next";
import { GoogleGenAI } from "@google/genai";

// Note: This API route may timeout for long-running video generations (up to 6 minutes).
// For production, consider using a background job or webhook approach.
export const config = {
  api: {
    responseLimit: false,
    bodyParser: {
      sizeLimit: '20mb', // Increased for reference images
    },
  },
  maxDuration: 600, // 10 minutes max (Next.js serverless function limit)
};

// TODO: Move API key to environment variable for production
const GEMINI_VEO_API_KEY = process.env.GEMINI_VEO_API_KEY || "AIzaSyDcEtzSyPBbVwR_Ygt9mkIUgownDyV9FRs";

// Initialize Google GenAI client
const ai = new GoogleGenAI({ apiKey: GEMINI_VEO_API_KEY });

// Helper function to parse data URL and extract image bytes and mime type
function parseDataUrl(dataUrl: string): { imageBytes: string; mimeType: string } | null {
  if (!dataUrl || typeof dataUrl !== "string") return null;
  
  // Match data URL format: data:[<mediatype>][;base64],<data>
  const match = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
  if (!match) return null;
  
  return {
    mimeType: match[1],
    imageBytes: match[2],
  };
}

// Helper function to create a reference image object for Veo 3.1
function createReferenceImage(dataUrl: string, referenceType: "asset" | "style" = "asset") {
  const parsed = parseDataUrl(dataUrl);
  if (!parsed) return null;
  
  return {
    image: {
      imageBytes: parsed.imageBytes,
      mimeType: parsed.mimeType,
    },
    referenceType,
  };
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({ ok: false, error: "Method not allowed" });
  }

  try {
    // Support both structured input (from Ad Builder) and simple prompt (legacy)
    const { 
      prompt, // Legacy: simple text prompt
      // Structured input from Ad Builder
      product_name,
      brand_name,
      style,
      duration,
      aspect_ratio,
      quality, // "standard" (720p) or "high" (1080p)
      final_video_prompt, // Generated by script generator
      voiceover_script,
      headline,
      subtext,
      // Reference images (product images and brand logo)
      product_images, // Array of data URLs or image URLs
      brand_logo, // Data URL or image URL
      hero_image, // Selected hero product image
    } = req.body;

    // Check if reference images are provided and build reference image array
    const hasReferenceImages = !!(hero_image || brand_logo || (product_images && product_images.length > 0));
    const referenceImages: Array<{ image: { imageBytes: string; mimeType: string }; referenceType: string }> = [];
    
    if (hasReferenceImages) {
      console.log('Reference images provided. Building reference images for Veo 3.1...');
      
      // Add hero/product image as primary reference (asset type)
      if (hero_image) {
        const heroRef = createReferenceImage(hero_image, "asset");
        if (heroRef) {
          referenceImages.push(heroRef);
          console.log('Added hero image as reference');
        }
      }
      
      // Add brand logo as reference (asset type)
      if (brand_logo) {
        const logoRef = createReferenceImage(brand_logo, "asset");
        if (logoRef) {
          referenceImages.push(logoRef);
          console.log('Added brand logo as reference');
        }
      }
      
      // Add additional product images (up to 3 total references allowed by Veo 3.1)
      if (product_images && Array.isArray(product_images)) {
        for (const imgUrl of product_images) {
          if (referenceImages.length >= 3) break; // Veo 3.1 supports up to 3 reference images
          if (imgUrl === hero_image) continue; // Skip if already added as hero
          
          const prodRef = createReferenceImage(imgUrl, "asset");
          if (prodRef) {
            referenceImages.push(prodRef);
            console.log('Added product image as reference');
          }
        }
      }
      
      console.log(`Total reference images prepared: ${referenceImages.length}`);
    }

    // Use structured prompt if available, otherwise fall back to simple prompt
    let videoPrompt: string;
    let videoDuration: number = 5;
    
    // Use the aspect ratio selected by the user; video is generated accordingly
    // Supported: 9:16, 16:9, 4:5 (enforced via prompt; API accepts prompt-only for aspect)
    let videoAspectRatio: string = "9:16";
    if (aspect_ratio && typeof aspect_ratio === "string") {
      videoAspectRatio = aspect_ratio.trim();
      if (!["9:16", "16:9", "4:5"].includes(videoAspectRatio)) {
        videoAspectRatio = "9:16"; // fallback if unknown value
      }
    }
    
    // Veo 3.1 resolution support
    // Reference: https://ai.google.dev/gemini-api/docs/video?example=dialogue#resolution
    // Supported: "720p", "1080p" (8s only), "4k" (8s only)
    // Map user quality selection to resolution
    let videoResolution: string | null = null;
    const videoDurationForResolution = duration || 6;
    if (quality === "high" || quality === "1080p") {
      // 1080p is only available for 8-second videos
      if (videoDurationForResolution === 8) {
        videoResolution = "1080p";
      } else {
        // Fall back to 720p if duration is not 8 seconds
        videoResolution = "720p";
      }
    } else if (quality === "standard" || quality === "720p" || !quality) {
      videoResolution = "720p";
    } else if (quality === "4k") {
      // 4k is only available for 8-second videos
      if (videoDurationForResolution === 8) {
        videoResolution = "4k";
      } else {
        videoResolution = "720p";
      }
    }

    if (final_video_prompt) {
      // Structured input from Ad Builder
      videoDuration = duration || 6;
      
      // Map style to creative animation/visual style descriptions for Veo 3.1
      const styleDescriptions: Record<string, { prefix: string; details: string }> = {
        // Animation styles
        "Stop Motion": {
          prefix: "A charming stop-motion animation style",
          details: "Use tactile, handcrafted stop-motion animation aesthetic. Objects should move with characteristic stop-motion jerkiness. Include subtle imperfections that make it feel handmade. Miniature set design with careful attention to tiny details."
        },
        "3D Animation": {
          prefix: "A polished 3D animated",
          details: "High-quality 3D CGI animation with smooth, fluid movements. Pixar/Disney-level rendering quality. Rich textures, dynamic lighting, and expressive character/object animation."
        },
        "2D Animation": {
          prefix: "A vibrant 2D animated",
          details: "Clean vector-style 2D animation with bold colors and smooth motion. Modern motion graphics aesthetic with shape morphing and dynamic transitions."
        },
        "Motion Graphics": {
          prefix: "A sleek motion graphics",
          details: "Professional motion graphics with geometric shapes, kinetic typography, and smooth transitions. Clean, modern aesthetic with bold colors and dynamic movement."
        },
        // Cinematic styles
        "Cinematic": {
          prefix: "A cinematic, high-production",
          details: "Film-quality cinematography with dramatic lighting, shallow depth of field, smooth camera movements. Professional color grading, anamorphic lens flares, and cinematic aspect."
        },
        "Product Close-up": {
          prefix: "A premium product showcase",
          details: "Macro-level product cinematography with extreme attention to detail. Dramatic lighting highlighting product features, rotating shots, and luxurious presentation. Studio-quality with seamless backgrounds."
        },
        "Lifestyle": {
          prefix: "A lifestyle-focused",
          details: "Authentic, aspirational lifestyle footage. Natural lighting, real-world settings, relatable scenarios. Warm, inviting color palette with candid, unposed feel."
        },
        "Luxury": {
          prefix: "An elegant, luxury",
          details: "High-end luxury aesthetic with sophisticated lighting, premium materials, and refined composition. Slow, deliberate camera movements. Rich blacks, gold accents, and exclusive atmosphere."
        },
        // Creative styles
        "Whimsical": {
          prefix: "A whimsical, playful",
          details: "Magical, dreamlike quality with fantastical elements. Soft, pastel colors, floating particles, and enchanting atmosphere. Imaginative and delightful visual storytelling."
        },
        "Retro": {
          prefix: "A retro-styled",
          details: "Vintage aesthetic with film grain, color shifts, and nostalgic feel. VHS-style effects, 80s/90s color palette, and period-appropriate typography."
        },
        "Minimalist": {
          prefix: "A minimalist, clean",
          details: "Ultra-clean aesthetic with lots of white space. Simple, elegant compositions with limited color palette. Focus on essential elements only, no clutter."
        },
        "Bold & Energetic": {
          prefix: "A bold, high-energy",
          details: "Dynamic, fast-paced visuals with vibrant colors. Quick cuts, zoom effects, and energetic motion. Urban, youthful aesthetic with street-style influences."
        },
        "Neon": {
          prefix: "A neon-lit, cyberpunk-inspired",
          details: "Glowing neon lights, dark backgrounds, and futuristic aesthetic. Vibrant pinks, blues, and purples. Reflective surfaces and urban night atmosphere."
        },
        // Legacy style mappings (for backward compatibility)
        "Fast & Punchy": {
          prefix: "A fast-paced, high-energy",
          details: "Quick cuts, dynamic transitions, and punchy editing. High-energy visuals with bold colors. Fast zoom effects, quick reveals, and impactful moments. Perfect for attention-grabbing social media ads."
        },
        "Premium & Cinematic": {
          prefix: "A premium, cinematic",
          details: "Film-quality cinematography with dramatic lighting, shallow depth of field, smooth camera movements. Professional color grading, anamorphic lens flares, and cinematic aspect. Luxury brand aesthetic."
        },
        "UGC / Influencer": {
          prefix: "An authentic, user-generated content style",
          details: "Natural, authentic look as if filmed on a smartphone by a real person. Slightly imperfect framing, natural lighting, genuine and relatable feel. Influencer/creator aesthetic that feels organic and trustworthy."
        },
      };

      // Get style description or create a default
      const normalizedStyle = style?.trim() || "Cinematic";
      const styleConfig = styleDescriptions[normalizedStyle] || {
        prefix: `A ${normalizedStyle.toLowerCase()}`,
        details: `${normalizedStyle} visual style with professional quality and attention to detail.`
      };
      
      // Build comprehensive prompt with style integrated into the opening
      let enhancedPrompt = `${styleConfig.prefix} ${videoDuration}-second video ad in ${videoAspectRatio} aspect ratio format.\n\n`;
      
      // Add product and brand context
      if (product_name || brand_name) {
        enhancedPrompt += `Product: ${product_name || "Product"}${brand_name ? ` | Brand: ${brand_name}` : ""}\n\n`;
      }

      // Add detailed style requirements
      enhancedPrompt += `VISUAL STYLE - ${normalizedStyle.toUpperCase()}:\n`;
      enhancedPrompt += `${styleConfig.details}\n\n`;
      
      // Add the generated video prompt
      enhancedPrompt += `${final_video_prompt}\n\n`;
      
      // Add aspect ratio and duration constraints explicitly in the prompt
      const aspectRatioDesc: Record<string, string> = {
        "9:16": "Vertical/Portrait (mobile-first)",
        "16:9": "Horizontal/Landscape (widescreen)",
        "4:5": "Portrait/Square (Instagram Feed)",
        "1:1": "Square",
      };
      
      enhancedPrompt += `CRITICAL REQUIREMENTS:\n`;
      
      // Strong aspect ratio enforcement with text-safe zones
      if (videoAspectRatio === "9:16") {
        enhancedPrompt += `- Aspect Ratio: STRICTLY 9:16 VERTICAL/PORTRAIT format (1080x1920 or equivalent). This is a mobile-first vertical video.\n`;
        enhancedPrompt += `- Frame composition: Vertical orientation, tall and narrow. All content must be optimized for vertical viewing.\n`;
        enhancedPrompt += `- Camera angles: Use vertical-friendly shots - close-ups, vertical pans, top-to-bottom reveals.\n`;
        enhancedPrompt += `- TEXT SAFE ZONES for 9:16:\n`;
        enhancedPrompt += `  * Primary text area: Upper third (15-35% from top), centered horizontally\n`;
        enhancedPrompt += `  * Secondary text area: Lower third (65-85% from top), centered\n`;
        enhancedPrompt += `  * Avoid: Bottom 10% (covered by UI), top 5% (status bar), left/right 10% edges\n`;
        enhancedPrompt += `  * Headlines: Large, centered, in upper safe zone\n`;
        enhancedPrompt += `  * Subtitles/CTA: Lower safe zone with padding from bottom edge\n`;
      } else if (videoAspectRatio === "16:9") {
        enhancedPrompt += `- Aspect Ratio: STRICTLY 16:9 HORIZONTAL/LANDSCAPE format (1920x1080 or equivalent). This is a widescreen video.\n`;
        enhancedPrompt += `- Frame composition: Horizontal orientation, wide format. All content optimized for landscape viewing.\n`;
        enhancedPrompt += `- Camera angles: Use horizontal-friendly shots - wide shots, horizontal pans, left-to-right reveals, establishing shots.\n`;
        enhancedPrompt += `- TEXT SAFE ZONES for 16:9:\n`;
        enhancedPrompt += `  * Title safe: Inner 90% of frame (5% margin all sides)\n`;
        enhancedPrompt += `  * Action safe: Inner 93% of frame\n`;
        enhancedPrompt += `  * Primary text: Lower third (60-80% from top), left-aligned or centered\n`;
        enhancedPrompt += `  * Headlines: Can be center-frame or rule-of-thirds positioned\n`;
        enhancedPrompt += `  * Avoid: Extreme corners, very top/bottom edges\n`;
      } else if (videoAspectRatio === "4:5") {
        enhancedPrompt += `- Aspect Ratio: STRICTLY 4:5 PORTRAIT format (1080x1350 or equivalent). This is optimized for Instagram Feed.\n`;
        enhancedPrompt += `- Frame composition: Portrait orientation, taller than square. All content optimized for 4:5 vertical feed.\n`;
        enhancedPrompt += `- Camera angles: Use portrait-friendly shots - close-ups, vertical pans, top-to-bottom reveals; avoid extreme wide horizontal framing.\n`;
        enhancedPrompt += `- TEXT SAFE ZONES for 4:5:\n`;
        enhancedPrompt += `  * Safe area: Inner 90% (5% margin all sides)\n`;
        enhancedPrompt += `  * Primary text: Upper third or center, horizontally centered\n`;
        enhancedPrompt += `  * CTA text: Lower portion, above bottom 10%\n`;
        enhancedPrompt += `  * Headlines: Centered, large enough to read on mobile feed\n`;
      } else {
        enhancedPrompt += `- Aspect Ratio: ${videoAspectRatio} (${aspectRatioDesc[videoAspectRatio] || "Custom"} format)\n`;
      }
      
      enhancedPrompt += `- Duration: Exactly ${videoDuration} seconds\n`;
      
      // Add resolution requirement in prompt (since REST API doesn't support resolution parameter)
      if (videoResolution) {
        enhancedPrompt += `- Resolution: ${videoResolution} (${videoResolution === "1080p" ? "Full HD" : videoResolution === "720p" ? "HD" : "4K"} quality)\n`;
        if (videoResolution === "1080p" || videoResolution === "4k") {
          enhancedPrompt += `- Note: ${videoResolution} resolution requires 8-second duration for optimal quality\n`;
        }
      } else {
        enhancedPrompt += `- Resolution: 720p (HD quality)\n`;
      }
      
      enhancedPrompt += `- Optimized for ${videoAspectRatio === "9:16" ? "mobile viewing (Instagram Reels, TikTok, YouTube Shorts)" : videoAspectRatio === "16:9" ? "desktop viewing (YouTube Ads)" : videoAspectRatio === "4:5" ? "Instagram Feed posts" : "social media feeds"}\n`;
      
      // Add instructions about using reference images
      // Since Files API upload requires complex multipart handling, we use detailed prompt descriptions
      if (hasReferenceImages) {
        enhancedPrompt += `\nVISUAL REQUIREMENTS (Based on provided product images and brand assets):\n`;
        if (hero_image) {
          enhancedPrompt += `- The product should be the primary visual focus, prominently featured and clearly visible throughout the video.\n`;
          enhancedPrompt += `- Match the exact appearance, colors, and details of the product as shown in the provided product images.\n`;
          enhancedPrompt += `- Use cinematic product photography techniques: dramatic lighting, shallow depth of field, premium composition.\n`;
          enhancedPrompt += `- The product must appear exactly as it looks in the reference images - maintain product accuracy and visual consistency.\n`;
        }
        if (brand_logo) {
          enhancedPrompt += `- Include the brand logo naturally in the video composition (e.g., bottom corner, on product packaging, or as a subtle watermark).\n`;
          enhancedPrompt += `- Ensure the logo is visible but doesn't obstruct the main product or content.\n`;
          enhancedPrompt += `- Logo should appear in the final 2 seconds as a brand moment.\n`;
          enhancedPrompt += `- Use the exact brand logo design, colors, and style from the provided brand assets.\n`;
        }
        if (product_images && product_images.length > 1) {
          enhancedPrompt += `- Use multiple product angles/views if available to showcase the product comprehensively.\n`;
          enhancedPrompt += `- Showcase different aspects of the product from various angles to highlight its features.\n`;
        }
        enhancedPrompt += `- Maintain brand consistency with colors, style, and aesthetic from the provided brand assets.\n`;
        enhancedPrompt += `- Ensure product accuracy - the product must appear exactly as shown in the reference images.\n`;
        enhancedPrompt += `- Avoid stock photo aesthetics - this must look like a custom, professional product shoot.\n`;
        enhancedPrompt += `- Match the visual style, lighting, and composition of the provided product images.\n`;
      }
      
      // Add premium quality requirements
      enhancedPrompt += `\nPREMIUM QUALITY REQUIREMENTS:\n`;
      enhancedPrompt += `- Cinematic visual style: professional lighting, smooth camera movements, shallow depth of field\n`;
      enhancedPrompt += `- Brand polish level: Match the quality of Apple, Stripe, or Linear product commercials\n`;
      enhancedPrompt += `- Avoid: stock photos, generic templates, PowerPoint-style layouts, cartoon illustrations, white backgrounds with floating icons\n`;
      enhancedPrompt += `- Motion: Smooth, minimal, cinematic transitions at 24-30fps. No bouncing text or flashy effects.\n`;
      enhancedPrompt += `- Typography baseline: Modern, clean fonts; high contrast against backgrounds; maximum 6 words per text element\n`;
      enhancedPrompt += `- Text rendering: All on-screen text must be razor-sharp, properly anti-aliased, never blurry or pixelated\n`;
      enhancedPrompt += `- Composition: Clean, uncluttered frames with intentional negative space for text placement\n`;
      enhancedPrompt += `- Color grading: Consistent, cinematic color palette throughout; ensure text colors complement the grade\n`;

      // Add voiceover/narration as spoken audio (Veo 3.1 native audio generation)
      // Using dialogue format: A narrator says, 'text here'
      if (voiceover_script && typeof voiceover_script === "string" && voiceover_script.trim()) {
        enhancedPrompt += `\nAUDIO & VOICEOVER:\n`;
        enhancedPrompt += `A professional narrator speaks with a confident, ${style?.toLowerCase().includes('energetic') ? 'energetic' : style?.toLowerCase().includes('luxury') ? 'sophisticated' : 'warm and engaging'} tone:\n`;
        enhancedPrompt += `'${voiceover_script.trim()}'\n`;
        enhancedPrompt += `The narration should be clear, well-paced, and synchronized with the visual action.\n`;
        enhancedPrompt += `Include subtle background music that complements the tone - ${style?.toLowerCase().includes('energetic') ? 'upbeat electronic beat' : style?.toLowerCase().includes('luxury') ? 'elegant ambient music' : 'modern, positive background music'}.\n`;
      } else {
        // No voiceover - add background music only
        enhancedPrompt += `\nAUDIO:\n`;
        enhancedPrompt += `Include ${style?.toLowerCase().includes('energetic') ? 'upbeat electronic music with a rhythmical beat' : style?.toLowerCase().includes('luxury') ? 'elegant, sophisticated ambient music' : 'modern, positive background music'} that enhances the visual experience.\n`;
      }

      // Add on-screen text instructions if provided (displayed text overlays)
      if (headline || subtext) {
        enhancedPrompt += `\nON-SCREEN TEXT OVERLAYS - PREMIUM TYPOGRAPHY:\n`;
        
        // Determine style-appropriate text treatment
        const isLuxury = style?.toLowerCase().includes('luxury') || style?.toLowerCase().includes('premium') || style?.toLowerCase().includes('elegant');
        const isBold = style?.toLowerCase().includes('bold') || style?.toLowerCase().includes('energetic') || style?.toLowerCase().includes('neon');
        const isMinimal = style?.toLowerCase().includes('minimal') || style?.toLowerCase().includes('clean');
        
        // Typography style based on ad style
        const fontStyle = isLuxury 
          ? "elegant serif or thin sans-serif (like Didot, Playfair Display, or Helvetica Neue Light)"
          : isBold 
            ? "bold, impactful sans-serif (like Montserrat Bold, Bebas Neue, or Impact)"
            : isMinimal
              ? "clean, lightweight sans-serif (like Inter, SF Pro, or Helvetica Neue)"
              : "modern, professional sans-serif (like Proxima Nova, Gotham, or Open Sans)";
        
        enhancedPrompt += `\nTYPOGRAPHY STYLE:\n`;
        enhancedPrompt += `- Font family: ${fontStyle}\n`;
        enhancedPrompt += `- Letter spacing: ${isLuxury ? "wide tracking (0.1em)" : isBold ? "tight tracking (-0.02em)" : "normal tracking"}\n`;
        enhancedPrompt += `- Text rendering: Crisp, anti-aliased, sharp edges\n`;
        
        if (headline) {
          enhancedPrompt += `\nHEADLINE TEXT: '${headline}'\n`;
          enhancedPrompt += `- Timing: Appear at 0.5-1 seconds, display for 2-3 seconds\n`;
          enhancedPrompt += `- Font size: Large, ${isLuxury ? "40-60pt equivalent" : isBold ? "60-80pt equivalent, extra bold weight" : "48-64pt equivalent"}\n`;
          enhancedPrompt += `- Font weight: ${isLuxury ? "Light or Regular (300-400)" : isBold ? "Bold or Black (700-900)" : "Semi-bold (600)"}\n`;
          enhancedPrompt += `- Color: ${isLuxury ? "White or gold (#FFFFFF or #D4AF37)" : isBold ? "High contrast (white on dark, or vibrant color)" : "White (#FFFFFF) with subtle drop shadow"}\n`;
          
          // Position based on aspect ratio
          if (videoAspectRatio === "9:16") {
            enhancedPrompt += `- Position: Centered horizontally, upper third of frame (20-35% from top)\n`;
            enhancedPrompt += `- Safe zone: Keep 10% margin from left/right edges\n`;
          } else if (videoAspectRatio === "16:9") {
            enhancedPrompt += `- Position: Lower third of frame (60-75% from top), left-aligned or centered\n`;
            enhancedPrompt += `- Safe zone: Keep 5% margin from all edges (title safe area)\n`;
          } else {
            enhancedPrompt += `- Position: Center of frame, slightly above middle\n`;
            enhancedPrompt += `- Safe zone: Keep 8% margin from edges\n`;
          }
          
          enhancedPrompt += `- Animation: ${isLuxury ? "Elegant fade in (0.5s ease-out), subtle scale from 98% to 100%" : isBold ? "Dynamic slide up with slight bounce, or glitch reveal" : "Smooth fade in (0.3s), gentle slide from bottom (20px)"}\n`;
          enhancedPrompt += `- Exit: ${isLuxury ? "Gentle fade out" : "Quick fade (0.2s) or slide away"}\n`;
        }
        
        if (subtext) {
          enhancedPrompt += `\nSUBTEXT: '${subtext}'\n`;
          enhancedPrompt += `- Timing: Appear 0.3-0.5 seconds after headline, display for 2 seconds\n`;
          enhancedPrompt += `- Font size: Medium, ${isLuxury ? "24-32pt equivalent" : "20-28pt equivalent"}\n`;
          enhancedPrompt += `- Font weight: ${isLuxury ? "Light (300)" : "Regular or Medium (400-500)"}\n`;
          enhancedPrompt += `- Color: ${isLuxury ? "Subtle white or light gray (#FFFFFF or #E0E0E0)" : "White with 90% opacity"}\n`;
          enhancedPrompt += `- Position: Directly below headline with ${isLuxury ? "generous spacing (24px gap)" : "tight spacing (12px gap)"}\n`;
          enhancedPrompt += `- Animation: Follow headline animation style, delayed by 0.2s\n`;
        }
        
        // Text effects for readability
        enhancedPrompt += `\nTEXT EFFECTS FOR READABILITY:\n`;
        if (isLuxury) {
          enhancedPrompt += `- Subtle drop shadow: 0 2px 8px rgba(0,0,0,0.3)\n`;
          enhancedPrompt += `- Optional: thin gold underline accent for headline\n`;
        } else if (isBold) {
          enhancedPrompt += `- Strong drop shadow: 0 4px 12px rgba(0,0,0,0.5)\n`;
          enhancedPrompt += `- Optional: text stroke/outline for extra pop\n`;
          enhancedPrompt += `- Consider: color gradient or glow effect for neon style\n`;
        } else {
          enhancedPrompt += `- Clean drop shadow: 0 2px 4px rgba(0,0,0,0.25)\n`;
          enhancedPrompt += `- Ensure contrast ratio of at least 4.5:1 against background\n`;
        }
        
        // Background treatment if needed
        enhancedPrompt += `- If text overlaps busy visuals: add subtle dark gradient overlay or frosted glass blur behind text\n`;
        enhancedPrompt += `- Text must ALWAYS be readable - never place over similar-colored backgrounds without treatment\n`;
        
        // Final text quality requirements
        enhancedPrompt += `\nTEXT QUALITY REQUIREMENTS:\n`;
        enhancedPrompt += `- All text must be perfectly sharp and crisp (no blur or pixelation)\n`;
        enhancedPrompt += `- Text should feel integrated into the video, not pasted on top\n`;
        enhancedPrompt += `- Maintain consistent typography throughout the video\n`;
        enhancedPrompt += `- Maximum 6-8 words per text element for quick readability\n`;
        enhancedPrompt += `- Text animations should be smooth (60fps), not janky or stuttering\n`;
      }
      
      videoPrompt = enhancedPrompt;
    } else if (prompt && typeof prompt === "string" && prompt.trim()) {
      // Legacy: simple text prompt — use user-selected aspect ratio
      const aspectLabel =
        videoAspectRatio === "9:16"
          ? "9:16 (Vertical/Mobile-first format)"
          : videoAspectRatio === "16:9"
            ? "16:9 (Horizontal/Landscape format)"
            : videoAspectRatio === "4:5"
              ? "4:5 (Portrait/Instagram Feed format)"
              : videoAspectRatio;
      videoPrompt = `Create a high-conversion video ad in ${videoAspectRatio} aspect ratio for social media.
Aspect Ratio: STRICTLY ${videoAspectRatio} — ${aspectLabel}.
Style: Professional, commercial-grade cinematography with high visual impact.
Target: Social media platforms (Instagram Reels, TikTok, YouTube Shorts, YouTube Ads, Instagram Feed).
Requirements:
- Strong visual hook in the first 1.5 seconds
- Clear, readable text overlays (positioned for ${videoAspectRatio} framing)
- Dynamic, engaging motion
- Professional production quality
- Optimized for ${videoAspectRatio === "16:9" ? "desktop/landscape" : "mobile/portrait"} viewing
- Native audio generation
- Keep it concise and engaging (aim for quick, impactful content)

User Request: ${prompt}`;
    } else {
      return res.status(400).json({ ok: false, error: "Either 'prompt' or structured input is required" });
    }

    // Call Veo 3.1 using Google GenAI SDK with reference images and aspect ratio support
    // Reference: https://ai.google.dev/gemini-api/docs/video?example=dialogue
    console.log('Starting Veo 3.1 video generation...');
    console.log('Requested duration:', videoDuration);
    console.log('Prompt length:', videoPrompt.length);
    console.log('Aspect ratio:', videoAspectRatio);
    console.log('Reference images count:', referenceImages.length);

    // Determine if we need video extension for longer videos (10s or 15s)
    // Veo 3.1 base video max is 8 seconds, extension adds 7 seconds
    // - 6s or 8s → generate directly
    // - 10s → generate 4s base, extend once (4+7=11s ≈ 10s)
    // - 15s → generate 8s base, extend once (8+7=15s)
    const needsExtension = videoDuration > 8;
    let baseDuration: number;
    if (videoDuration <= 8) {
      baseDuration = videoDuration;
    } else if (videoDuration === 10) {
      baseDuration = 4; // 4s + 7s extension = 11s (closest to 10s)
    } else {
      // 15s or longer
      baseDuration = 8; // 8s + 7s extension = 15s
    }

    console.log('Base duration for generation:', baseDuration);
    console.log('Needs extension:', needsExtension);

    // Build the config object for generateVideos
    // Map aspect ratio to SDK-supported format (Veo 3.1 supports "16:9" and "9:16")
    // For 4:5, we use "9:16" as the closest supported format but enforce 4:5 in prompt
    const sdkAspectRatio = videoAspectRatio === "4:5" ? "9:16" : videoAspectRatio;
    
    const generateConfig: any = {
      // Always include aspect ratio from user selection
      aspectRatio: sdkAspectRatio,
      // Set resolution (720p for extension, as 1080p only supports 8s without extension)
      resolution: needsExtension ? "720p" : (videoResolution || "720p"),
      // Set number of videos
      numberOfVideos: 1,
    };
    
    // Add reference images if available (Veo 3.1 supports up to 3 reference images)
    if (referenceImages.length > 0) {
      generateConfig.referenceImages = referenceImages;
      console.log('Using reference images for video generation');
    }

    console.log('Generate config:', { 
      aspectRatio: generateConfig.aspectRatio,
      resolution: generateConfig.resolution,
      hasReferenceImages: !!generateConfig.referenceImages,
      referenceImagesCount: generateConfig.referenceImages?.length || 0,
    });

    // Start video generation with the SDK
    let operation: any;
    try {
      operation = await ai.models.generateVideos({
        model: "veo-3.1-generate-preview",
        prompt: videoPrompt,
        config: generateConfig,
      });
      console.log('Base video generation operation started');
    } catch (sdkError: any) {
      console.error("Veo SDK error:", sdkError);
      return res.status(500).json({
        ok: false,
        error: `Video generation failed: ${sdkError.message || "Unknown SDK error"}`,
        details: sdkError.toString(),
      });
    }

    // Poll the operation until it's complete
    // According to docs: Min latency 11 seconds, Max 6 minutes during peak hours
    const maxAttempts = 60; // 60 attempts * 10 seconds = 10 minutes max
    let attempts = 0;

    while (!operation.done && attempts < maxAttempts) {
      attempts++;
      console.log(`Polling attempt ${attempts}/${maxAttempts}...`);
      
      // Wait 10 seconds before checking again (as per documentation)
      await new Promise((resolve) => setTimeout(resolve, 10000));

      try {
        // Poll the operation status using SDK
        operation = await ai.operations.getVideosOperation({
          operation: operation,
        });
      } catch (pollError: any) {
        console.error("Polling error:", pollError);
        throw new Error(`Failed to poll operation: ${pollError.message}`);
      }
    }

    if (!operation.done) {
      return res.status(408).json({
        ok: false,
        error: "Video generation timed out. Please try again.",
      });
    }

    console.log('Base video generation completed!');

    // Extract video from completed operation
    let generatedVideo = operation.response?.generatedVideos?.[0];
    if (!generatedVideo?.video) {
      console.error("Unexpected operation response structure:", JSON.stringify(operation, null, 2));
      return res.status(500).json({
        ok: false,
        error: "Video generation completed but video not found in response",
        rawResponse: operation,
      });
    }

    // If we need extension for longer videos (10s or 15s), extend the base video
    if (needsExtension) {
      console.log('Extending video for longer duration...');
      console.log('Target duration:', videoDuration, 'seconds');
      
      // Create an extension prompt that continues the video naturally
      const extensionPrompt = `Continue the video seamlessly. Extend this ${product_name ? `${product_name} ` : ""}product video ad naturally, maintaining the same visual style, pacing, and quality. ${voiceover_script ? `Continue with the message: "${voiceover_script}"` : ""}`;
      
      try {
        // Start video extension operation
        // The video from the previous generation is passed as input
        let extensionOperation = await ai.models.generateVideos({
          model: "veo-3.1-generate-preview",
          video: generatedVideo.video, // Pass the previously generated video
          prompt: extensionPrompt,
          config: {
            numberOfVideos: 1,
            resolution: "720p", // Extension only supports 720p
          },
        });
        
        console.log('Video extension operation started');
        
        // Poll for extension completion
        let extensionAttempts = 0;
        while (!extensionOperation.done && extensionAttempts < maxAttempts) {
          extensionAttempts++;
          console.log(`Extension polling attempt ${extensionAttempts}/${maxAttempts}...`);
          
          await new Promise((resolve) => setTimeout(resolve, 10000));
          
          try {
            extensionOperation = await ai.operations.getVideosOperation({
              operation: extensionOperation,
            });
          } catch (pollError: any) {
            console.error("Extension polling error:", pollError);
            throw new Error(`Failed to poll extension operation: ${pollError.message}`);
          }
        }
        
        if (!extensionOperation.done) {
          console.warn('Video extension timed out, using base video instead');
          // Continue with base video if extension times out
        } else {
          console.log('Video extension completed!');
          
          // Use the extended video
          const extendedVideo = extensionOperation.response?.generatedVideos?.[0];
          if (extendedVideo?.video) {
            generatedVideo = extendedVideo;
            console.log('Using extended video');
          } else {
            console.warn('Extended video not found in response, using base video');
          }
        }
      } catch (extensionError: any) {
        console.error("Video extension error:", extensionError);
        console.log('Falling back to base video due to extension error');
        // Continue with base video if extension fails
      }
    }

    // Download the final video (either base or extended)
    let videoBase64: string;
    let videoUrl: string;

    try {
      // Try to get video bytes directly if available
      if (generatedVideo.video.videoBytes) {
        videoBase64 = generatedVideo.video.videoBytes;
        videoUrl = `data:video/mp4;base64,${videoBase64}`;
        console.log('Video obtained from videoBytes');
      } 
      // Otherwise, download using fetch with API key
      else if (generatedVideo.video.uri) {
        console.log('Downloading video from URI...');
        const videoResponse = await fetch(generatedVideo.video.uri, {
          headers: {
            "x-goog-api-key": GEMINI_VEO_API_KEY,
          },
        });

        if (!videoResponse.ok) {
          return res.status(500).json({
            ok: false,
            error: `Failed to download video: ${videoResponse.statusText}`,
            videoUri: generatedVideo.video.uri,
          });
        }

        const videoBuffer = await videoResponse.arrayBuffer();
        videoBase64 = Buffer.from(videoBuffer).toString("base64");
        videoUrl = `data:video/mp4;base64,${videoBase64}`;
        console.log('Video downloaded successfully');
      } else {
        return res.status(500).json({
          ok: false,
          error: "No video data or URI available in response",
        });
      }
    } catch (downloadError: any) {
      console.error("Video download error:", downloadError);
      return res.status(500).json({
        ok: false,
        error: `Failed to download video: ${downloadError.message}`,
      });
    }

    // Calculate actual duration based on whether extension was used
    const actualDuration = needsExtension 
      ? (baseDuration + 7) // Extended video: base + 7 seconds
      : baseDuration;

    return res.status(200).json({
      ok: true,
      videoUrl,
      videoUri: generatedVideo.video.uri || null,
      duration: actualDuration,
      requestedDuration: videoDuration,
      aspectRatio: videoAspectRatio,
      usedReferenceImages: referenceImages.length > 0,
      wasExtended: needsExtension,
    });
  } catch (error: any) {
    console.error("Video generation error:", error);
    return res.status(500).json({
      ok: false,
      error: error.message || "Failed to generate video",
    });
  }
}

